UN-OCHA/common_design

package-lock.json
=> CD-159 results of npm audit fix for lodash

common_design.info.yml, common_design.theme
- do not use classy button css
- remove preprocess for Views exposed filter form
=> IASC-561 improvements to base theme

common_design.info.yml
comment out jquery library definition for common_design, leaving there in case needed for testing
=> CD-183 remove jquery library

js/cd-dropdown.js, package-lock.json, package.json
To get dropdowns working in logged-in Drupal
=> CD-183 drupal context

common_design.libraries.yml, js/cd-dropdown.js, js/cd-polyfill.js
- Conditionally loading for browsers that do not support es6 modules
- Set as dependency for cd-dropdown
- Remove unneeded polyfills and testing-related code
=> CD-186 JS polyfills

sass/cd/cd-header/_cd-user-menu.scss
rule for where there is only the user menu and it is expanded
=> CD-98 user menu when expanded

components/cd-grid/cd-grid.css, components/cd-grid/cd-grid.html, components/cd-grid/cd-grid.html.twig
update grid component based on https://github.com/UN-OCHA/common_design_system/pull/4
=> CD-187 grid component

package-lock.json, package.json
include version of kind-of as per github security alert recommendation
=> Dependency update for kind-of

components/cd-button/cd-button.css, components/cd-button/cd-button.html, components/cd-button/cd-button.html.twig, components/cd-table/cd-table.css, components/cd-table/cd-table.html, components/cd-table/cd-table.html.twig
=> CD-187 update table and button components

components/cd-hero/cd-hero.css
Add feature queries for object fit for better PE hero component image display, fixes #67
=> IASC-646 Better PE hero component

common_design.libraries.yml, components/cd-filters/cd-filters.html, components/cd-filters/cd-filters.html.twig, components/cd-filters/cd-filters.js, js/cd-polyfill.js
- Polyfill for closest
- Add dependencies for polyfill and css-vars ponyfill for the components that need them
- fix Filter component, remove unneeded class, check for element
=> Better IE support

js/cd-dropdown.js
Additional changes to the cd-dropdown.js file.
=> [CD-201] dropdown conditions - additions

templates/cd/cd-footer/cd-footer-menu.html.twig
https://humanitarian.atlassian.net/browse/CD-209
=> [CD-209] fix twig comment

package-lock.json, package.json
https://github.com/UN-OCHA/common_design/network/alert/package-lock.json/object-path/open
=> Dependency update for object-path

sass/cd/cd-header/_cd-ocha.scss, templates/cd/cd-header/cd-ocha.html.twig
Use cd-button utility classes for "See all" button
New / Old:
=> CD-142 OCHA Services button

common_design.breakpoints.yml, sass/cd/_cd-variables.scss
For use in Responsive image module and in SASS for larger viewport widths
=> CD-224 xxl breakpoint

templates/cd/cd-footer/cd-copyright.html.twig, templates/cd/cd-footer/cd-mandate.html.twig, templates/cd/cd-header/cd-ocha.html.twig
Based on recent GHO work https://github.com/UN-OCHA/gho-site/pull/4/files
=> CD-223 wrap strings in translation tags

components/cd-button/cd-button.css
set display on a.cd-button so OCHA Services "See all" link displays 100% on mobile
=> CD-142 follow up to OCHA Services button

components/README.md, components/cd-alert/README.md, components/cd-alert/cd-alert.css, components/cd-alert/cd-alert.html, components/cd-alert/cd-alert.html.twig
=> CD-226 cd-alert

templates/cd/cd-header/cd-ocha.html.twig
Ticket: CD-257
Simply makes the "See all" link label translatable.
=> [CD-257] Make the see all link label translatable in the OCHA services

components/README.md
Review the `cd-author` component
See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-author
=> CD-226 cd-author

components/README.md
Review the `cd-byline` component
See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-byline
=> CD-226 cd-byline

components/README.md
Review the cd-caption component
See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-hero and https://feature.commondesign-unocha-org.ahconu.org/demo#cd-banner for examples of the caption
=> CD-226 cd-caption

components/README.md
Review the `cd-read-more` component
See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-read-more
=> CD-226 cd-read-more

components/README.md, templates/page--demo.html.twig
Review of the `cd-block-title` component
See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-block-title for an example
=> CD-226 cd-block-title

components/README.md, components/cd-banner/README.md
Review of the cd-banner component
See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-banner for examples
=> CD-226 cd-banner

components/README.md
Review of the `cd-title-list` component
See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-title-list for an example
=> CD-226 cd-title-list

components/README.md
Review of the `cd-link-list` component
See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-link-list for an example
=> CD-226 cd-link-list

components/README.md, components/cd-card/README.md
Review of the `cd-card` component
See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-card for an example
=> CD-226 cd-card

components/README.md
Review of the `cd-pagination` component
See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-pagination for an example
=> CD-226 cd-pagination

components/cd-card/cd-card.html, components/cd-card/cd-card.html.twig, components/cd-event/cd-event.html, components/cd-event/cd-event.html.twig, components/cd-grid/README.md, components/cd-grid/cd-grid.css, components/cd-grid/cd-grid.html, components/cd-grid/cd-grid.html.twig, components/cd-link-list/cd-link-list.html, components/cd-link-list/cd-link-list.html.twig
From https://github.com/UN-OCHA/common_design_system/pull/28
with additional improvements based on https://github.com/UN-OCHA/common_design/pull/175
=> CD-275 Grid component improvements

components/cd-toc/README.md, components/cd-toc/cd-toc.css, components/cd-toc/cd-toc.html, components/cd-toc/cd-toc.html.twig, components/cd-typography/cd-typography.html, components/cd-typography/cd-typography.html.twig
Improve TOC component https://github.com/UN-OCHA/common_design_system/pull/30
=> AR-227 TOC component

sass/base/_typography.scss, sass/cd/_cd-variables.scss, sass/cd/cd-header/_cd-logo.scss, sass/cd/cd-header/_cd-nav.scss, sass/cd/cd-layout/_cd-layout.scss
Remove `sass-lint:disable` rules
=> CD-184 sass-lint cleanup

_tests/FooterMenu.test.js, _tests/MainMenuDropdown.test.js, _tests/MobileMenu.test.js, _tests/OCHADropdown.test.js, _tests/SearchDropdown.test.js, common_design_subtheme/_tests/FooterMenu.test.js, common_design_subtheme/_tests/MainMenuDropdown.test.js, common_design_subtheme/_tests/MobileMenu.test.js, common_design_subtheme/_tests/OCHADropdown.test.js, common_design_subtheme/_tests/SearchDropdown.test.js
Based on https://github.com/UN-OCHA/common-design-site/pull/79
=> CD-193 Correct JS linting errors for tests

_tests/FooterMenu.test.js, _tests/MainMenuDropdown.test.js, _tests/MobileMenu.test.js, _tests/OCHADropdown.test.js, _tests/SearchDropdown.test.js, _tests/_env/index.js, _tests/_env/local.js, _tests/_env/production.js, common_design_subtheme/_tests/_env/index.js, common_design_subtheme/_tests/_env/local.js, common_design_subtheme/_tests/_env/production.js, common_design_subtheme/jest-puppeteer.config.js, jest-puppeteer.config.js, package-lock.json, package.json
let's see if travis accepts it
=> [OPS-7440] make E2E play with common-design-site nicely

_tests/FooterMenu.test.js, _tests/HeadingOne.test.js, _tests/MainMenuDropdown.test.js, _tests/MobileMenu.test.js, _tests/OCHADropdown.test.js, _tests/SearchDropdown.test.js, _tests/_DebugEnv.test.js, _tests/_env/index.js, common_design_subtheme/_tests/FooterMenu.test.js, common_design_subtheme/_tests/HeadingOne.test.js, common_design_subtheme/_tests/MainMenuDropdown.test.js, common_design_subtheme/_tests/MobileMenu.test.js, common_design_subtheme/_tests/OCHADropdown.test.js, common_design_subtheme/_tests/SearchDropdown.test.js, common_design_subtheme/_tests/_env/index.js, jest-puppeteer.config.js, jest.config.js, jest.setup.js, package.json
Consolidating my feedback from #223 into a PR to that same branch. Welcome back!
=> OPS-7440: E2E continued

components/README.md, components/cd-bleed/README.md
Approving the bleed component.
=> [CD-226] approve bleed component

components/README.md, components/cd-dropdown/README.md
and fix some line-length/ whitespace issues
=> [CD-226] approve cd-dropdown component

components/README.md, components/cd-image-grid/README.md, components/cd-image-grid/cd-image-grid.html
Changes in the .html file are almost all indentation, to include the cd-image-grid class.
=> [CD-226] approve image-grid

components/README.md, components/cd-typography/README.md
Looks good, just noting two 'extra' layers of html which I don't think are useful:
```
<main role="main" id="main-content" class="cd-container">
<div class="cd-layout-content">
```
=> [CD-226] approve component

components/cd-button/cd-button.css
Applies `cursor: pointer;` to all CD Buttons.
=> CD-299: apply cursor:pointer to all CD Buttons

CHANGELOG.md, common_design_subtheme/browserconfig.xml
Move file from base theme to sub theme, adjust path so image comes from sub theme
=> CD Issue 249 browserconfig

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
- manually update xmldom from github package
=> CD-298 Dependency updates

CHANGELOG.md, CONTRIBUTING.md, pull_request_template.md
1. Add portion for Release Notes format to CONTRIBUTING.md and mention adding item to changelog
2. Add pull request template with prompts and checklists
=> CD-334 contributing

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
Dependency update for `set-value` from Dependabot alert
Update `package.json` in sub theme and run `npm i` to avail of dependency update
=> CD-289 dependency updates

CHANGELOG.md, CONTRIBUTING.md, README.md, common_design_subtheme/README.md
Mention Drupal 9 in README (I already updated the repo description)
Whilst helping the GMS team to find the latest resources for their Drupal 7 -> Drupal 9 upgrade we noticed a number of places that still say "Drupal 8" for the CD. Now it says both!
=> CD-341: update docs to mention D9 plus other small tweaks

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
Add nth-check as dev dependency as per Dependabot security alert, and regenerate package lock file
1. Add `nth-check` as a dev dependency  "nth-check": ">=2.0.1"
1. Run `npm i` to regenerate lock
=> CD-289 Dependency updates for nth-check

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
Add json-schema as dev dependency, regenerate lock file
=> CD-289 add json-schema as dev dependency

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
:heavy_check_mark: Improvement (non-breaking change which iterates on an existing feature)
CD-289 to close this issue, finally replace xmldom package from github with proper package, update core-js to prevent warnings, run `npm audit fix` and `npm update`
Run `npm i` to update packages
=> CD-289 update xmldom and core-js to latest, npm audit fix and npm update

CHANGELOG.md, README.md
In order to close CD-196 I've added some of what was documented on the ticket to the README
=> CD-196 Expand Testing section in README

CHANGELOG.md, CONTRIBUTING.md, README.md, common_design.libraries.yml, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, components/cd-form/cd-form--preview.css, package-lock.json, package.json, templates/form/form--node-preview-form-select.html.twig, templates/form/form--term-preview-form-select.html.twig
=> v6.0.0 Release 2022-03-09

CONTRIBUTING.md, pull_request_template.md
A few updates to the docs based on recent addition of conventional commits.
=> Add Conventional Commits item to PR checklist

CHANGELOG.md, package-lock.json, package.json
=> Tagging v7.0.1

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 7.1.0

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 7.2.0

CHANGELOG.md, package-lock.json, package.json
I want all the latest changes for the WP CD update.
Refs: CD-406
=> chore(release): 7.2.1

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 7.3.0

components/cd-form/cd-form.css
Refs: CD-420
Remove declarations for z-index and position which seem to have been added accidentally
Fixes a display issue where the Search submit button doesn't appear until it's in focus.
When one clicks on the Search and enters the input fields, the submit button should be visible.
When one clicks the Search, the submit button is not visible. See https://web.brand.unocha.org/
- Notice the Search submit is not visible …
=> CD-420 Fix search submit button

common_design.theme
=> feat: Rename my account

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 7.4.0

CHANGELOG.md, package-lock.json, package.json
Releasing a patch to make user menu upgrades easier.
=> chore(release): 7.4.1

CONTRIBUTING.md, README.md, common_design_subtheme/README.md
@left23 review for FYI only. No action needed.
Trying to sync the docs with the state of the project, consolidate a few sections, and add audience indicators where it seems helpful.
Literally none. Don't even need to run composer.
=> docs: major updates to all docs

common_design.info.yml, composer.json
Refs: CD-432
This ensures that the https://www.drupal.org/project/stable is installed when installing the CD theme.
The `stable` theme was removed from D10 and moved to a contrib project.
The `stable` theme is installed in `themes/contrib/stable` on D9/D10. For D9 sites, it is then used instead of the `core/themes/stable`. This should not have any impact unless the site is applying some patches to the core stable theme.
=> chore: add drupal stable theme dependency

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 8.0.0

components/cd-block-title/cd-block-title.css, components/cd-bullet-list/cd-bullet-list.css, components/cd-facets/cd-facets.css, components/cd-form/cd-form.html, components/cd-form/cd-form.html.twig, components/cd-styled-list/cd-styled-list.css, components/cd/cd-resets/cd-typography.css
Some follow-ups to fix minor issues with #391 
How does the proposed change impact existing implementations? What action is needed to accommodate these changes?
=> [CD-462] follow ups

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
=> chore(release): 8.1.0

components/cd-toc/README.md, components/cd-toc/cd-toc.css, components/cd-toc/cd-toc.html.twig, templates/layout/page--demo.html.twig
Fixing regressions on ToC, updating the Demo example to use sidebars instead of floats.
1. Demo page should have two functional ToCs: the column-based at the top, and a single-col in a sidebar under the `cd-toc` section.
1.
1.
No impact. Less stuff will be broken now.
=> [CD-412] ToC fixes

common_design_subtheme/components/cd/cd-header/cd-logo.css
Third time's a charm?
Refs: CD-475, df1976a
#396 #406
=> fix: remember to unset custom logo for desktop

CHANGELOG.md, package-lock.json, package.json
* CD Disclosure component ([fb2ad8b](https://github.com/UN-OCHA/common_design/commit/fb2ad8b93e2afe28f1811f920eefdfb579bb375f))
=> chore(release): 9.2.0

package-lock.json
npm updates
No impact to existing subthemes.
=> chore(security): npm dependencies - caniuse, browserlist, postcss, semver

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
=> chore(release): 9.2.1

components/cd-nodes/cd-nodes.css
Refs: CD-513
Few lines of CSS to make our unpublished nodes look nicer:
https://github.com/UN-OCHA/common_design/assets/254753/18fd4fba-000a-4415-b3ee-b85c01ac618d
1. Look at an unpublished node (probably with an account with admin perms)
2.
3.
No impact to existing sites. No steps to upgrade.
=> fix(admin): nicer-looking unpublished styles

components/cd/cd-header/cd-site-header.css, components/cd/cd-other/cd-layout--content.css
Refs: CD-493
Checking an old comment about the w3 css validator, it pointed out a couple of minor syntax errors.
1. https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Finteragencystandingcommittee.org%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=
How does the proposed change impact existing implementations? What action is needed to accommodate these changes?
Minimal.
- [ ? (I think so) ] I have …
=> chore: minor fixes picked up by css-validator

composer.json
Refs: updates
Allow latest version of composer/installers.
Shouldn't be any - just allows updating another package.
=> chore: allow updating installers

CHANGELOG.md, package-lock.json, package.json
* **sdc:** Snap SDC ([4406afd](https://github.com/UN-OCHA/common_design/commit/4406afd55ff353ef96d505942c71dbba34e11b37))
* **sdc:** Video SDC ([c741003](https://github.com/UN-OCHA/common_design/commit/c7410038765895b57afee15c4a586f0476080490))
* allow multiple versions of composer installers  ([2f0ca65](https://github.com/UN-OCHA/common_design/commit/2f0ca65ef9b3400861c9c96b928785b64ef1297f))
=> chore(release): 9.3.0

README.md, common_design_subtheme/README.md
Updating README to remove unhelpful or irrelevant info.
=> CD-506 Update README

README.md
Refs: CD-514, 25775b78, #448
Changes the README to show our recommended HTML for font-loading in case someone implements CD outside Drupal.
1. Just check the README and compare to a Drupal install.
README only. No change to any implementation.
=> docs: update example markup for fonts in README

README.md, common_design_subtheme/README.md, libraries/README.md, libraries/cd-dropdown/README.md
Updates to docs based on content within our old Google Drive (now SharePoint) but in general trying to move developer notes about the theme into the README / instructions here.
Docs only. No testing needed.
Docs only. No impact.
=> [CD-553] moving docs to this repo

common_design_subtheme/package-lock.json, img/icons/sprite.symbol.html, package-lock.json
Update `svg-sprite`to get our vulns back down to zero.
1. Run `npm run svg:sprite`
2. Or check this diff because I ran it as part of the commit (see date change)
No impact.
=> chore(deps-dev): update svg-sprite

common_design.theme
Refs: CD-555
Rewritten an if-clause
1. It's only triggered on very few 404s, I tried visiting urls similar to those which gave this error but couldn't reproduce it.
2. To test, check the syntax.
How does the proposed change impact existing implementations? What action is needed to accommodate these changes?
No action needed.
=> chore: fix unexpected error

libraries/cd/cd-other/cd-print.css
Refs: RWR-473
- :heavy_check_mark:Bug fix (non-breaking change which fixes an issue)
Ensure long links wrap properly.
=> fix: ensure long links wrap properly

libraries/cd-search--inline/cd-search--inline.html.twig
Refs: CD-557
Make sure search text is translated in twig template.
- [ x ] I have followed the Conventional Commits guidelines.
=> chore: translate string for search

.github/workflows/checks.yml
=> chore: Bump actions to avoid breakage.
