package-lock.json, package.json
If they remain in devDepencencies, they will not be installed when the production container is built with `NODE_ENV=production` and cause a build failure.
See https://github.com/UN-OCHA/common-design-site/commit/ed18c886e0f47463a7c4eb61d1a3898d234211e7/checks?check_suite_id=389465190
=> 📌 [OPS-6125] Move required deps from devDeps, so they are present for production builds.

common_design.theme, templates/page--demo.html.twig
To avoid twig errors (and site breaking) when /demo page is loaded, and components module is not installed.
=> CD-187 components module check if enabled

common_design.libraries.yml
so sub theme libraries are ordered after base theme libraries and can override, fixes #66
=> IASC-646 css weight should be component not theme 

js/cd-dropdown.js
To prevent conflicts with other elements using the aria-expanded true and false for display, fixes #74
=> CD-204 Expand selector to cd-dropdown elements only

templates/block/block--system-menu-block--account.html.twig, templates/block/block--system-menu-block--help.html.twig, templates/block/block--system-menu-block--main.html.twig
Ticket: https://humanitarian.atlassian.net/browse/CD-209
This tries to consolidate the aria-labelledby and id attributes for the CD header menus (notably the main menu had 2 ids).
I also added translation for the 'Menu' button label (cd-toggable attribute on the main menu).
Initially I was thinking of removing the `navigation` role but as we still supports IE11, we need to keep it (See https://www.drupal.org/project/drupal/issues/2655794#comment-12161581).
=> [CD-209] Fix CD header menus aria-labelledby and id attributes

templates/cd/cd-header/cd-ocha.html.twig
Ticket: https://humanitarian.atlassian.net/browse/CD-209
This simply changes the `aria-labelledby` to `aria-label` as the dropdown toggling button is added by javascript and so may not be present (if javascript is not available). 
An alternative would be to add a visually hidden `h2` like it's done for the other menus in the header. That might even be better to make sense of the list of links when consuming a page with the cd-header with something other than a standard modern browser.
=> [CD-209] Change aria label for OCHA services menu

templates/field/image.html.twig
Ticket: https://humanitarian.atlassian.net/browse/CD-209
Context:  some images rendered via the `image.html.twig` template don't have an `alt` attribute. This can happen for example with media images migrated from Drupal 7 if they didn't have an alt value.
This overrides the `image.html.twig` template to check for the `alt` attribute and add an empty one if not present for better accessibility and validity.
Note: that is not an issue in the common design theme as other base themes have the same problem but the fix being easy, I think that would be a good addition to the common design base theme.
An alternative could be to implement a `hook_preprocess_image()` to add the `alt` attribute if not present but that's not necessarily better than the template.
=> [CD-209] Ensure images have an alt tag

templates/maintenance-page.html.twig, templates/page--404.html.twig, templates/page--demo.html.twig, templates/page.html.twig
Ticket: https://humanitarian.atlassian.net/browse/CD-212
Currently the target of the skip to content link is an `<a>` tag with the `main-content` id. This is an old method and not the recommended one, which is to add the id directly to the main sectioning element (`main` in our case): https://webaim.org/techniques/skipnav/
Drupal has an [open issue](https://www.drupal.org/project/drupal/issues/2784311) to patch core that's taking forever to be added because of the impact on bartik and other themes. That's however not an issue for us so we can change the `page.html.twig` template in the base common design theme.
=> [CD-212] Change the skip to content link target to be more in accordance with latest recommendations

common_design.info.yml, common_design.libraries.yml
Sorta fixes #98 because inconsistent indentation was confusing but all dependencies were loading because it seems indentation does not matter for children with hyphens
works:
```
cd-menu:
js:
js/cd-menu.js: {}
dependencies:
- common_design/cd-dropdown
```
also works:
```
cd-menu:
js:
js/cd-menu.js: {}
dependencies:
- common_design/cd-dropdown
```
**Drupal has indented children.**
https://www.drupal.org/docs/theming-drupal/adding-stylesheets-css-and-javascript-js-to-a-drupal-theme#s-declaring-dependencies
https://www.drupal.org/docs/8/theming-drupal-8/defining-a-theme-with-an-infoyml-file#dependencies
=> make indentation for dependencies consistent

common_design.theme, templates/page--404.html.twig
Replace text string with `page.content` region so generic error message appears on a 404 page *I assume the text string was there to provide a friendlier message and remains a nice option for specific implementations, but can be added to the sub theme instead.
Add class `page-error` and `page-error--404` to body class for 403 and 404 status codes, to facilitate styling of these pages.
=> CD-issue 99 & 100 Error page templates

common_design.theme, components/cd-search/cd-search.html.twig, templates/block/block--language-block.html.twig, templates/block/block--search-form-block.html.twig, templates/cd/cd-header/cd-ocha.html.twig, templates/navigation/links--language-block.html.twig
As per [CD-221](https://humanitarian.atlassian.net/browse/CD-221), I've correct the errors from WAVE tool.
For the search and language switcher, I added an ID to the block h2, and its value as aria-labelledby value.
For the OCHA Services and also language switcher block, I've added menuitem as role to the li elements. However I could use a second opinion on this. It's unclear to me whether the role=menu should be used, and if not, the menuitem role is not relevant.
=> CD-221 broken aria-labelledby and missing menuitem role

components/cd-button/cd-button.css
While working on [HID-2169](https://humanitarian.atlassian.net/browse/HID-2169), I was using CD Buttons on both `<button>` and `<a>` elements which are horizontally aligned on a single row. The reason is because two buttons are submit/reset for a form, and the third was a hyperlink labeled "Cancel"
When I loaded the form, the Cancel button had more vertical space, leading the button to be taller. It ended up being a different `line-height` for links versus buttons. The PR further normalizes the value from `normalize.css` which sets buttons to `line-height: 1.15` and ensures that button-looking links also end up the same visual size.
=> CD-226: explicitly set line-height to normalize's default value

templates/navigation/menu--account.html.twig, templates/navigation/menu--help.html.twig, templates/navigation/menu--main.html.twig
Ticket: CD-255
This does 2 thinks: 
1. Reset the "attributes" variable before passing it to the nested menus.
This prevents attributes added to the top menu elements to be added to the nested menus which is the equivalent of what `stable` and `classy` themes for example do via a `if/else`:
```twig
{% if menu_level == 0 %}
<ul{{ attributes }}>
{% else %}
<ul>
{% endif %}
```
2. Add `span` around the `title` when displaying links in the navigation menu. This is for compatibility for GHO and ease styling (ex: centering the title vertically).
=> [CD-255] Fix menu attributes and add compatibility for GHO

components/README.md
Review the cd-button component
See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-button for examples
This `cd-button` is also used in the OCHA Services menu.
=> CD-226 cd-button

common_design.info.yml, common_design.theme
Ticket: CD-263, CD-265
This simply adds the requirement for compatibility with Drupal 9 to the v1.
It also replaces the [`User::getUsername()` deprecated function]( https://api.drupal.org/api/drupal/core%21modules%21user%21src%21Entity%21User.php/function/User%3A%3AgetUsername/8.2.x).
PR for the v2: https://github.com/UN-OCHA/common_design/pull/171
=> [CD-263] Make theme compatible with Drupal 9 - v1

common_design.info.yml, common_design.theme
Ticket:  CD-263
This simply adds the requirement for compatibility with Drupal 9 to the v2.
It also replaces the [`User::getUsername()` deprecated function]( https://api.drupal.org/api/drupal/core%21modules%21user%21src%21Entity%21User.php/function/User%3A%3AgetUsername/8.2.x), after porting the user menu cache fix from https://github.com/UN-OCHA/common_design/pull/137
PR for the v1: https://github.com/UN-OCHA/common_design/pull/172
=> [CD-263] Make theme compatible with Drupal 9 - V2

common_design.theme, templates/content/node--full.html.twig
Ticket: CD-273
This refactors a bit the way to display the page title on node pages.
*Note: there are some unrelated changes which are just coding standards fixes*
There is now a setting on `/admin/appearance/settings/common_design` to select for which node view mode, the `page title` block should be pre-rendered and displayed inside the node `<article>` instead of using the default placement of the page title block.
By default, the behavior is enabled for the node "full" view mode.
The function that retrieves the block render array `common_design_get_block_render_array()` now stores the list of regions in which the block was supposed to be rendered so that it can be removed from the page via `common_design_remove_rendered_blocks()` called in the `common_design_preprocess_page()`.
The …
=> [CD-273] Refactor page title for nodes

components/cd-form/cd-form.css
Noticed on POCAM
Drupal's `.field label` class is missing a style tho bold it. Missing after Classy was removed.
=> CD-270 Bold field label

common_design.info.yml, common_design.theme, common_design_subtheme/README.md, common_design_subtheme/common_design_subtheme.info.yml.example
Some experimenting with Twig namespace control of nested theme directories using the Components module for namespacing.
To prevent the `Template not defined` error when only the base theme is activated.
The base theme serves a few purposes. It demonstrates the component library and the Common Design header and footer (acting like a living styleguide), and ships the sub theme for implementations to use. In most cases, a sub theme will be activated and in the `themes/custom` directory so this issue will not be relevant.
This is for the exception that is the CD Demo site, which only shows the base theme.
```
Twig\Error\LoaderError: Template "@common_design_subtheme/cd/cd-header/cd-header.html.twig" is not defined in "themes/contrib/common_design/common_design_subtheme/templates/layout/page.ht …
```
=> OPS-7412 subtheme inside the base theme issues

common_design_subtheme/sass/cd/_cd-variables.scss, package-lock.json, package.json, sass/base/_typography.scss, sass/cd/_cd-variables.scss
Upgrades fonts to always use HTTPS. See ticket for some links and references for why.
=> CD-288: explicitly upgrade font requests to HTTPS

_tests/FooterMenu.test.js, _tests/MainMenuDropdown.test.js, _tests/MobileMenu.test.js, _tests/OCHADropdown.test.js, _tests/SearchDropdown.test.js, _tests/_env/local.js, _tests/_env/production.js, common_design_subtheme/_tests/FooterMenu.test.js, common_design_subtheme/_tests/MainMenuDropdown.test.js, common_design_subtheme/_tests/MobileMenu.test.js, common_design_subtheme/_tests/OCHADropdown.test.js, common_design_subtheme/_tests/SearchDropdown.test.js, common_design_subtheme/_tests/_env/local.js, common_design_subtheme/_tests/_env/production.js, common_design_subtheme/jest-puppeteer.config.js, jest-puppeteer.config.js
I put the OCHADropdown test into our HID-2212 branch for testing and while inspecting the code found a couple things to tighten up. The tests still pass against https://web.brand.unocha.org whenI run locally.
I've copied all config changes into HID repo to keep them in sync.
=> CD-193: modify E2E tests

common_design.theme
Tickets: IASC-683, CD-283
This fixes the issue with the double page titles and local tasks.
The problem was happening when the rendered node was cached and the page was rebuilt then the `hook_preprocess_node().` was not called and the list of rendered blocks was not populated so the function called in `hook_preprocess_page()` couldn't remove the page title and local tasks from the "page title" region.
This solves the problem by storing the rendered block info (id, region) as a cache tag which then can be retrieved whether the rendered node is cached or not.
This also adds more appropriate cache metadata to the page title and local tasks blocks.
=> [IASC-683][CD-283] Fix the cacheability of the page title and local tasks block

common_design.theme
Ticket: CD-283
This fixes the previous fix to fix the double page titles...
It uses a different approach as we cannot rely on the cache metadata to determine if the page title and local tasks blocks were rendered (ex: IASC which renders the node in a block making the cache metadata for the node unavailable in the hook_preprocess_page).
Instead it retrieves the view mode for the node in the `hook_preprocess_page()` and if it's one of the selected view modes in the theme settings, then it hides the page title and local tasks blocks from their page region.
Tested the fix against IASC, CD site, AR, SLT ([needs a patch in subtheme](https://github.com/UN-OCHA/slt8-site/pull/26)), ODSG and GHO.
Like previously, the same approach as what is done for the page title and local tasks blocks can be …
=> [CD-283] Fix double page titles

_tests/_env/index.js, common_design_subtheme/_tests/_env/index.js
I gave some bad, untested code suggestions in the other PR https://github.com/UN-OCHA/common_design/pull/221. This is fully tested. Set `NODE_ENV` to any value at all (including empty string) and this should work.
=> [OPS-7440] output baseUrl safely

components/README.md, components/cd-toc/README.md
Just noting that the .html template, unlike the others, is a full html document with head and body sections (and 'cd-toc--float-left' class while .twig template has 'cd-toc--float-right'.
=> [CD-226] approve component

common_design.theme
New feature: Twig template suggestions for any Views Display being rendered.
While implementing CD on a project, I had a particularly protracted battle with Drupal trying to get some Twig templates to be recognized in regards to a specific Views Display. In the end, the code to enable the behavior was quite short and I'd like to add it to Common Design as a more dev-friendly default.
It either didn't render any suggestions at all, simply reporting that it pulled the CD `views-view.html.twig` or it listed the one option with no alternatives:
```html
```
This is a real example of a View with machine key `features` and Display machine key `embed_latest_4`:
```html
```
=> CD-269: add theme hook suggestions for any Views Display

common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
`css-what` as devDependency for `svg-sprite`
`trim-newlines` as devDependency for `stylelint-no-browser-hacks`
Drupal 9 has removed `stylelint-no-browser-hacks` https://www.drupal.org/project/drupal/issues/3144854 but so far this has not been applied to the Drupal 8 branch. https://git.drupalcode.org/project/drupal/-/blob/8.9.x/core/.stylelintrc.json#L4
Eventually we should be able to extend `core/.stylelintrc.json` (as we already do) but it won't include `stylelint-no-browser-hacks`
https://github.com/UN-OCHA/common_design/blob/main/.stylelintrc.json#L3
=> CD-298 Dependency updates

components/README.md, components/cd-grid/README.md
I might have garbled the todo in the README - please check it makes sense!
The last-child approach seems to make more sense when there's just one item in the last row. Where there's more than one, you get an 'extra line':
Is that as planned?
=> [CD-226] cd-grid review

CHANGELOG.md, common_design.theme, templates/content/node--full.html.twig
Ticket: CD-237
As discovered in https://humanitarian.atlassian.net/browse/IASC-716, there may be some occasions where a node is rendered in a view mode selected to use the page title block, outside of the node page, for example when indexing a rendered node with Search API.
Another problem with the current logic is that the node title and local tasks don't appear in the node edit page when using the CD theme for the edit forms.
This PR refines the logic to limit the use of the page title to node canonical and preview pages.
This is compatible with the current logic and so updating any site using the CD theme should be seamless.
**Test**
1. Update any site using the CD with the code from this branch.
2. Check that "full" is selected in the CD settings (should be by default).
3. Visit a …
=> [CD-327] Fix page title logic

common_design.theme, templates/content/node--full.html.twig
Ticket: CD-327
This fixes a flaw in the previous page title fix (https://github.com/UN-OCHA/common_design/pull/262) where the node title would be rendered as h2 instead of not being displayed in the template (ex: unselect the page title setting in the CD theme).
In addition this adds compatibility with node template overrides in sites using the CD theme like IASC: https://github.com/UN-OCHA/iasc8/blob/9a31465b063f9c0ac9383fbbb8905534794edc91/html/themes/custom/iasc_common_design/templates/node/node--full.html.twig#L91-L101.
**Full view mode in node page and preview**
1. Select "Full" as view mode to use the page title in the CD theme/subtheme settings
2. View a node, check that the title is using the page title template and is inside the `<article>`
3. Edit the node, click "preview" and …
=> [CD-327] Add compatibility with node template overrides

CHANGELOG.md, README.md, translations/README.md, translations/ar-common-design.po, translations/es-common-design.po, translations/fr-common-design.po
- Copy `.po` files from [common-design-site](https://github.com/UN-OCHA/common-design-site/tree/develop/translations) root to base theme and add note at the top of readme
Since the strings are related specifically to the CD Header and Footer UI, the translation files should be in the same place.
Translation files for Arabic, Spanish, and French for the CD Header and Footer are now part of the repo so any implementations using this as a base theme can avail of these and updates from now on.
=> CD-258 Translation files in base theme

pull_request_template.md
Add item to the PR template to prompt when changes to the base theme also need to be made in the sub theme.
I think this is something being overlooked, as https://humanitarian.atlassian.net/browse/CD-328?focusedCommentId=129222 points out.
Sub theme should be insync with base theme
Sub theme version is not updated past its initial copying from the base theme into `/themes/custom/` despite changes to the package.json …
=> CD-334 Add item about changes to sub theme in the PR checklist

.stylelintrc.json, CHANGELOG.md, common_design_subtheme/.stylelintrc.json
- Add `ch` unit to `unit-allowed-list` stylelint configuration
- Remove `unit-whitelist` from stylelint configuration as it is deprecated
- Remove `plugin/no-browser-hacks` from sub theme stylelint configuration. See [issues #265](https://github.com/UN-OCHA/common_design/issues/265). The base theme and sub theme are now tailored for >= Drupal 9.2
Closing some items in the backlog.
See #265 
After updating the node packages `npm i` we can run `npm run sass:lint` without deprecation warnings or missing plugin errors.
=> CD-329 Remove stylelint and unit-whitelist, and plugin/no-browser-hacks from sub theme

common_design.theme, common_design_subtheme/README.md, common_design_subtheme/templates/cd/cd-icons/cd-icons.html.twig, common_design_subtheme/templates/layout/html.html.twig, templates/cd/cd-icons/cd-icons.html.twig, templates/layout/html.html.twig
Refs: CD-373
- :heavy_check_mark: Breaking change (fix or feature that would cause existing functionality to not work as expected)
Include the icon SVG sprite via a template rather than via the `hook_preprocess_html()`.
The current "recommended" way to extend the SVG sprite in the subtheme is to implement a `hook_preprocess_html()` in the subtheme similarly to what is done in the base theme.
This hook approach means fetching and including the content of the SVG sprite on every page call depending on the caching settings of the site. 
When …
=> [CD-373] SVG sprite inclusion

CONTRIBUTING.md, package.json
Improves the release process by having `standard-version` skip creation of git tags, which we manage via GitHub UI.
When using the `npm run release` command, it should no longer create a git tag, but still update the CHANGELOG and also bump the version in package.json.
1. Run `npm run release -- --dry-run` on this branch. It should mention that it updated CHANGELOG and bumped the version, but should NOT mention creating a git tag.
There is no change to the base-theme, sub-theme, or any sub-theme implmementation.
=> [CD-380] ensure future releases skip creation of git tag

templates/navigation/menu--account.html.twig, templates/navigation/menu--help.html.twig, templates/navigation/menu--main.html.twig
Refs: CD-364
- :heavy_check_mark:Bug fix (non-breaking change which fixes an issue)
Ensure proper ID hierarchy in the account, help and main menu templates.
IDs were duplicated for children items across menu items, causing accessibility issues.
List item IDs should be unique now.
IDs are duplicated for children items across menu items.
1. Create menu entries with children for the main menu
2. Without this PR, checks the IDS, there should be duplicates like `cd-main-menu-item-1-1`.
3. With the change from this PR such IDs should be changed to `cd-main-menu-0-1-item-1` etc.
This should not have impacts on existing site that use the base theme `navigation/menu--main.html.twig`.
Sites like GHO-2022 overriding this template should path the template override with the changes from this PR.
=> [CD-364] Ensure proper ID hierarchy in menu templates

common_design.info.yml, common_design.libraries.yml, components/cd-nodes/README.md, components/cd-nodes/cd-nodes.css
When your user has sufficient permissions to view unpublished nodes, they will appear with a salmon background color instead of the default.
We keep applying this to many websites. This makes it official.
1. Log in as a user with permissions to view unpublished content (user/1 is an easy choice)
1. Create a new node and make sure the "Published" checkbox is NOT checked when you save.
1. Review the node and confirm that the light pink background-color is present.
If individual websites were applying this manually, they can remove that code if they wish. If the website had more complicated logic than checking for `.node--unpublished` then it might be necessary to leave the site-specific rules in place.
=> [CD-382] visual indicator for unpublished nodes

common_design_subtheme/css/brand.css, components/cd-button/cd-button.css, components/cd-button/cd-button.html, components/cd-button/cd-button.html.twig, css/brand.css
The CD Button component now uses `--brand` colors by default, allowing them to integrate better into the CD Header where one button is guaranteed to appear (OCHA Services menu).
1. Check this branch out somewhere and use as base-theme
2. Copy the sub-theme and enable it
3. Choose colors in sub-theme's `css/brand.css`
4. Review OCHA Services menu to see if button automatically uses brand colors
No impact to sub-themes.
=> [CD-388] Adopt brand colors in CD Button

templates/layout/page--404.html.twig, templates/layout/page--facets.html.twig
Refs: CD-401
-  Improvement (non-breaking change which iterates on an existing feature)
Since the template embed was not namespaced, it conflicts with any `page.html.twig` override files in the sub theme
This means the `page--facets.html.twig` main block was not being applied, thus we were not able to see the facets region, which is specific to the facet page template override.
Even when there is a sub theme enabled, the facets region from `page--facets.html.twig` should display.
Currently, when …
=> CD-401 fix: namespace the embeds so they do not conflict with sub theme overrides

templates/cd/cd-footer/cd-mandate.html.twig
Refs: CD-413
We used `UNOCHA` in a visually hidden span representing the footer logo. I spelled out the full org name.
a11y / seo
1. Inspect OCHA logo in footer and hunt around for the visually hidden name
There is no impact or remediation necessary for any website. If they overrode the template in a subtheme, this text won't change automatically. But it's basically a cosmetic change.
=> fix: avoid abbreviations in visually-hidden logo text

common_design.theme
Refs: CD-254
This is an attempt at simplifying the changes to the user menu introduced in the 7.4.0 version, requiring less to no changes for sites upgrading to that version while ensuring a consistent user menu across sites in the form:
```
My account
Edit my account
... (other actions)
Log out
````
With the changes in that PR, the `Edit my account` and `Log out` are automatically added as first and last links under the …
=> refactor: better account menu consistency across sites

common_design.info.yml, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json, sass/cd/cd-header/_cd-user-menu.scss
Avoid linting errors when committing CSS changes to individual implementations.
After upgrading a Drupal site to 9.5.x I noticed that new CSS changes could no longer pass linting. This seems to fix it.
Change and commit CSS error free.
1. Install this branch on a 9.5.x site — or — manually bump the subtheme of a 9.5.x site to have `stylelint-config-standard@29`
1.
1.
This will prevent the theme from working on 9.4.x or older (while still allowing 8.8.x or higher) but since 9.4 is EOL I don't consider it a breaking change.
=> build(deps): bump stylelint-config-standard to match Drupal 9.5.x

components/cd-toc/README.md, components/cd-toc/cd-toc.css
Refs: CD-412
Removed the float option (if you want a column for it, use a layout). It now expands to fill space by breaking the ToC into columns. For CD Demo, the items are an ordered list so the numbers make it a bit easier to follow. People can always override this behavior if they find it undesirable:
```css
@media (min-width: 576px) {
.cd-toc__list {
--cd-toc-cols: 1; /* override */
}
}
```
Sites using the float-related …
=> fix: remove float variant from ToC and increase columns

common_design_subtheme/package-lock.json, common_design_subtheme/package.json, components/cd/cd-resets/cd-typography.css
We noticed that the tabs got nudged around using the CD Spacious mode. This fixes it.
1. Log in so you get tabs somewhere
1. Load a page which applies `.cd-content--spacious` high enough in the DOM to affect the tabs
1. Load this branch and confirm the tabs look normal
No impact.
=> [CD-450] CD Spacious should not affect tabs

components/cd/cd-resets/cd-typography.css
Refs: CD-459
Bug fix for an overreaching breaking change I made to `<img>` in v8.0.0
Behavior of `<img>` is reverted to pre-8.0.0
=> fix: revert the disruptive display:block on img tags

CHANGELOG.md, package-lock.json, package.json
* **cd-tabs:** exclude tabs and styled lists from typography defaults ([61cb937](https://github.com/UN-OCHA/common_design/commit/61cb937fcae1d129056ed87958e3c355414857e8))
* **cd-typography:** revert the disruptive display:block on img tags ([04d768d](https://github.com/UN-OCHA/common_design/commit/04d768dd8bd87e3d257d6ae5da00a5a7a459ba72))
=> chore(release): 8.0.1

components/cd/cd-footer/cd-footer-copyright.css, components/cd/cd-footer/cd-footer-social.css, components/cd/cd-footer/cd-footer.css, components/cd/cd-header/cd-global-header.css, components/cd/cd-header/cd-header.css, components/cd/cd-header/cd-language-switcher.css, components/cd/cd-header/cd-logo.css, components/cd/cd-header/cd-ocha.css, components/cd/cd-header/cd-search.css, components/cd/cd-header/cd-user-menu.css, css/brand.css, templates/navigation/menu--account.html.twig, templates/navigation/menu--help.html.twig
Adopt `:focus-visible` styles in Header/Footer
The focus styles are less obtrusive for mouse users, which will hopefully mean that teams stop overriding them with harmful resets that remove the styles entirely, causing accessibility issues with the modified websites.
Additionally, keyboard navigation is more attractive and hopefully that translates to a UX improvement.
The Search dropdown also uses the same `:focus-visible` …
=> [CD-454] :focus-visible styles

components/cd/cd-footer/cd-footer-copyright.css, components/cd/cd-footer/cd-footer-mandate.css, components/cd/cd-footer/cd-footer-social.css, components/cd/cd-footer/cd-footer.css, components/cd/cd-header/cd-global-header.css, components/cd/cd-header/cd-header.css, components/cd/cd-header/cd-language-switcher.css, components/cd/cd-header/cd-logo.css, components/cd/cd-header/cd-nav.css, components/cd/cd-header/cd-ocha.css, components/cd/cd-header/cd-search--inline.css, components/cd/cd-header/cd-search.css, components/cd/cd-header/cd-user-menu.css, css/brand.css, templates/cd/cd-footer/cd-mandate.html.twig, templates/navigation/menu--account.html.twig, templates/navigation/menu--help.html.twig
Continuing to remove directional properties in favor of logical properties. This PR is limited to CD Header/Footer; the components can be cleaned up on an individual basis.
1. View an LTR page and an RTL page. Compare to them to each other, and web.brand.
1. Pretty much any change in appearance is a regression (exceptions following)
- **Footer mandate logo** has been intentionally adjusted. The logo had a vertical alignment …
=> [CD-453] RTL refactors

CHANGELOG.md, css/brand.css, package-lock.json, package.json
While updating WP starterkit by copying files from the base-theme, I noticed the focus styles didn't match. Now they do.
1. Use keyboard nav on a Drupa install with no sub-theme
2. Compare to one with untouched sub-theme.
No impact.
=> [CD-469] CSS Vars fix

CHANGELOG.md, components/cd/cd-header/cd-search.css
I noticed this while doing some WP upgrades. Screenshot in CD-469.
1. Use a smartphone with viewport in between 320px and 420px wide to toggle Search
1. Before PR, it will cause viewport overflow
1. After PR, no overflow
No impact.
=> [CD-469] fix overflow on search dropdown for viewports 320 > 420

common_design.theme
I suggest using the `drupal_static()` pattern instead of directly using PHPs built-in `static` keyword for keeping track of rendered page title blocks. This is inline with Drupals suggested use-case as described in https://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/function/drupal_static/10.0.x and it also makes it possible to clear the static cache if needed.
Using the diff module to compare revisions, …
=> Use drupal_static() instead of PHPs static keyword

common_design_subtheme/README.md, common_design_subtheme/common_design_subtheme.info.yml.example, common_design_subtheme/common_design_subtheme.libraries.yml, common_design_subtheme/components/cd/cd-header/cd-logo.css, common_design_subtheme/css/brand.css, components/cd/cd-header/cd-logo.css, components/cd/cd-header/cd-site-header.css, css/brand.css
- :heavy_check_mark: New feature (non-breaking change which adds functionality)
One of the most common tasks is to override the site logo. While doing some upgrades recently I botched it up, and decided that the `brand.css` really should be a home for the mobile logo as well. The PR makes it possible to override the mobile logo by specifying an image in the filesystem. The sub-theme has an override for CD Header enabled by default so that the variable in `brand.css` will be relative to the subtheme's …
=> [CD-475] Simplify how you override mobile logo

common_design_subtheme/common_design_subtheme.libraries.yml
A follow-up PR to https://github.com/UN-OCHA/common_design/pull/396
Had I tested it properly before approving, I would have caught this :)
The lack of `: {}` after `components/cd/cd-header/cd-logo.css` results in an error in the browser ` Warning: foreach() argument must be of type array|object, string given in /srv/www/html/core/lib/Drupal/Core/Asset/LibraryDiscoveryParser.php on line 179`
The other change - removing the …
=> CD-475 Mobile logo in subtheme follow-up

components/cd/cd-header/cd-user-menu.css, img/logos/ocha-lockup.svg, templates/block/block--language-block.html.twig, templates/block/block--system-branding-block.html.twig, templates/block/block--system-menu-block--account.html.twig, templates/block/block--system-menu-block--footer.html.twig, templates/block/block--system-menu-block--help.html.twig, templates/block/block--system-menu-block--main.html.twig, templates/cd/cd-footer/cd-copyright.html.twig, templates/cd/cd-footer/cd-footer-menu.html.twig, templates/cd/cd-footer/cd-footer.html.twig, templates/cd/cd-footer/cd-mandate.html.twig, templates/cd/cd-footer/cd-social-menu.html.twig, templates/cd/cd-header/cd-header.html.twig, templates/layout/html.html.twig, templates/layout/maintenance-page.html.twig, templates/layout/page--404.html.twig, templates/layout/page--demo.html.twig, templates/layout/page--facets.html.twig, templates/layout/page.html.twig, templates/navigation/menu--account.html.twig, templates/navigation/menu--help.html.twig
Improves screen reader performance by eliminating redundancies, or consolidating relevant properties. The results mean the screen reader announces far fewer words, while still announcing all the important roles and labels.
Each navigation section used to have a visually-hidden heading referenced with `aria-labelledby`. That markup caused every heading to effectively be announced twice (once for `aria-labelledby` and once …
=> [CD-476] Improve screen reading

components/cd-tabs/cd-tabs.css, components/cd-tabs/cd-tabs.html, components/cd-tabs/cd-tabs.html.twig, templates/navigation/menu-local-tasks.html.twig
Refs: CD-418, CD-478
For RWR I had revamped the tabs to use flexbox which brings automatic RTL support. For CD-476 I improved the screen reading of many navigational areas, and settled on a pattern that results in an informative but less verbose screen reading. This is a contribution from those two efforts.
The tabs look largely the same, but are spaced a bit more tightly in desktop (more tabs possible in same area), and …
=> [CD-418] improve a11y/RTL of CD Tabs

CHANGELOG.md, package-lock.json, package.json
* specify mobile logo via `--brand` variable ([2be5631](https://github.com/UN-OCHA/common_design/commit/2be56319b6aaa56f104307106d00a3ae53be304f))
* **a11y:** add header to announce copyright notice ([9f5bbb9](https://github.com/UN-OCHA/common_design/commit/9f5bbb98a1667d17726e483a050235a7048cde61))
* **a11y:** announce Footer nav in footer ([3a7f43f](https://github.com/UN-OCHA/common_design/commit/3a7f43fb13535a82d4d553b24a59ee2c278a97d4))
* **a11y:** announce Header/Footer in same manner ([459a33c](https://github.com/UN-OCHA/common_design/commit/459a33c01b68d45e07af89418f5554c8e9e411b2))
* **a11y:** announce Site Name and avoid announcing logo ([e517abb](https://github.com/UN-OCHA/common_design/commit/e517abb7a38e0a4800651e548f363c4c7aedab17))
* **a11y:** announce Social nav in footer …
=> chore(release): 8.2.0

components/cd-form/README.md, components/cd-form/cd-form.css
We had some collisions with [Admin Toolbar](https://www.drupal.org/project/admin_toolbar) and decided the easiest thing to do is prefix our selectors with `form`. All of our use-cases for this component involve true `<form>`s so it seems to be a safe modification.
1. Test on a Drupal install that uses forms (CD Demo, Sesame, RW)
1.
1.
We increased specificity so any CSS overrides might need to be adjusted. Simply add `form` …
=> fix: prevent CD Form from applying outside <form> elements

components/cd/cd-resets/cd-resets.css
- :heavy_check_mark: New feature (non-breaking change which adds functionality)
Either user preference, or browser resources can cause animations and transitions to be disabled.
1. Enable `prefers-reduced-motion: reduce` in your browser
1. Mouse over buttons to see if the transitions are eliminated
- No change to browsers with `prefers-reduced-motion: no-preference` (the default).
- Browsers with `prefers-reduced-motion: reduce` will actually see that preference respected now.
=> [CD-408] disable animations/transitions when unwanted

components/cd-article/cd-article.html, components/cd-article/cd-article.html.twig, components/cd-card/cd-card.css, templates/content/node--full.html.twig, templates/layout/page--facets.html.twig, templates/layout/page.html.twig
There used to be a little gap under every Card image. By setting the image to `display:block` we eliminate that gap. Now the visual appearance will match whatever you wrote in code. That is, if you have a flex `gap:1rem`, and a Card container `padding-top:1rem` then it will truly be 2rem instead of a little extra.
1. Check the demo
Before / after, with Flex item borders overlaid.
If you relied on an image to be …
=> [CD-481] card image gaps, ARIA roles, demo tweaks

common_design.libraries.yml, components/cd/cd-header/cd-ocha-services.js, templates/cd/cd-footer/cd-footer.html.twig
Reported to us in #413. Fixes #413.
1. Load branch and tab through document from the beginning.
2. Without the PR, OCHA Services gets highlighted after language, help, user menus.
3. After PR, OCHA Services is highlighted first.
No impact. The changed function is private to the base-theme Drupal behaviors.
=> [CD-486] Ensure tab order of Global Header matches visual order

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
* **a11y:** ensure tab order for OCHA Services matches visual order ([f75c659](https://github.com/UN-OCHA/common_design/commit/f75c65951eff83a45007b8ca3705cb34da7b6e67))
* **security:** stylelint upgraded ([21ea859](https://github.com/UN-OCHA/common_design/commit/21ea8591b076e21433b5a94f94d8da0aee419cd4))
=> chore(release): 9.0.1

components/cd/cd-footer/cd-footer-mandate.css
Other translations wrap to three real lines but EN had a two-letter orphan on the third line. This looks nicer.
=> [CD-487] collapse mandate to two lines in EN

components/cd-social-links/cd-social-links.html.twig, components/cd/cd-other/cd-skip-link.css
We noticed that some URL params aren't encoded in our example Twig for the CD Social Links. Now they are.
No action strictly necessary. Sites that have copied this template into an active twig override should manually encode URL params.
=> [CD-488] encode all URL params in CD Social Links example markup

components/cd-dropdown/README.md, components/cd-dropdown/cd-dropdown.html.twig, components/cd/cd-resets/cd-typography.css, templates/layout/page--demo.html.twig
Follow-up to #420 
CD Dropdown entry for Demo page, plus changes to README. I looked at the example URL from RW in #420 and tried to mostly replicate that functionality.
1. Visit the demo page and click "Dropdown" in the ToC
2. Try the button out. 
3.
No impact.
=> [CD-489] CD Dropdown example and README

common_design.theme
Refs: CD-492, https://github.com/UN-OCHA/numbers-site/pull/192
New syntax for sites upgrading to Drupal 10.1.x which has also been tested to work on Drupal 9.5.9
No impact.
=> fix: D10 updates to our 404/403 detection

CHANGELOG.md, package-lock.json, package.json
* allow to insert the toggler button after the toggable element ([018a236](https://github.com/UN-OCHA/common_design/commit/018a2366294b8d0182ba5ab58b550d5b78fae339))
* **a11y:** avoid `aria-haspopup` when using `data-cd-insert-after` attr ([bdabca0](https://github.com/UN-OCHA/common_design/commit/bdabca0f0f46ac004b7d5e33211f4d6b0dfcde91))
* auto-close dropdowns when they lose focus ([be95645](https://github.com/UN-OCHA/common_design/commit/be95645ba4fa3a9481ea57ac2cbcbf7e3b13e2f1))
* avoid breaking change for Disclosure pattern ([4379567](https://github.com/UN-OCHA/common_design/commit/437956730dcccf534c00224c4d217f40f963c918))
* change scope of auto-close listener to improve UX ([82fc78b](https://github.com/UN-OCHA/common_design/commit/82fc78bad7d67db7811b97583b612262948b0e82))
* …
=> chore(release): 9.1.0

templates/block/block--system-branding-block.html.twig, translations/ar-common-design.po, translations/es-common-design.po, translations/fr-common-design.po
Check1st scans flag this as an "medium" severity accessibility issue, as "Image suspected of redundant alt attribute".
https://docs.wcag.online/criteria/h2/
I made the change on UNOCHA sub theme and can confirm it resolves the issue.
1. Look at the existing markup for the logo on https://web.brand.unocha.org/
2. Notice the anchor title (actually a child span) and the img alt value match
3. Check out the branch and notice the img alt value also includes the word "logo"
This will remove the issue from the scans, thus decreasing the noise. And according to WGAG resolves an issue with "Critical " user impact.
- [x I have followed the Conventional Commits guidelines.
=> CD-504 Logo image suspected of redundant alt attribute

components/cd-typography/cd-typography.html, components/cd-typography/cd-typography.html.twig, components/cd/cd-resets/cd-typography.css
As described CD-498 this removes the rule to set the ol list style to decimal.
1. Check out this branch
2. Visit /demo#cd-typography and look for the nested ordered list element
3. Notice it uses numbers for all levels
4. In the inspector, add `type="i"` to the nested ol tag See types: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol#attributes
5. Notice the nested ol's items are using roman numerals.
No negative repercussions expected. When ordered lists are added via the WYSIWYG and they have a type, the type will apply.
=> CD-498 Remove ol list-style rule

common_design.theme
Adds Paragraphs-related theme suggestions in the following format:
```sh
paragraph--PARENT-ENTITY--PARAGRAPH.html.twig
paragraph--PARENT-ENTITY--PARENT-FIELD--PARAGRAPH.html.twig
```
1. Create a template in an existing installation with all the various entities and fields configured.
2. Rebuild cache
3. See if the template picks up automatically
No impact. This is a new theme suggestion and if you created the same one in …
=> [CD-419] Add paragraphs-related theme suggestions

.github/workflows/checks.yml, common_design_subtheme/.stylelintrc.json
I was making a new Drupal site with stock CD sub-theme and it wouldn't pass linting out of the box. It was a small amount of outdated Stylelint config.
I fixed it up and this branch also begins running the sub-theme's tests as well. This will help us achieve consistency and partly automates one of our checklist items having to do with copying over changes to the sub-theme.
1. See outcome of GitHub Action …
=> [CD-508] stylelint and more PR automation

components/cd/cd-header/cd-language-switcher.css, components/cd/cd-header/cd-nav.css
Increases the opacity of the active item underline for better visibility, uses consistent focus-visible styles so all items in header have the same style when tabbing with the keyboard.
1. Check out this branch and compare with https://web.brand.unocha.org
2. The Active trail and Active item should be preserved but the opacity increased for better visibility, also on mobile
3. The Main Menu keyboard tabbing should have a blue outline like the other elements, but the click focus should remain as before (we are distinguishing between focus and focus-visible now)
Update the base theme with the latest release when this PR is …
=> CD-500 Focus styles for main navigation

components/cd-social-links/cd-social-links.html.twig
While reviewing the Social Links I noticed the demo has two divs for announcements. One is totally unused and I probably left it there while developing the code and forgot about it. Its classname is totally absent from our codebase.
1. Load demo and click the 🔗  Social Link icon. If the message still pops up then it is fine.
2.
3.
No impact. This is for CD Demo page only.
=> fix: remove duplicate announcement element from CD Social links

CHANGELOG.md, package-lock.json, package.json
* Focus styles for main navigation #441 CD-500
* Twitter icon updated for CD Social Links #438 CD-502
* remove duplicate announcement element from CD Social links #442
* **ci:** run JS linter on base-theme PRs #437 CD-507
* **ci:** run tests on sub-theme during PRs #440 CD-508
=> chore(release): 9.2.2

common_design.theme
Refs: CD-514
Adds the `media="print"` attribute to the primary Google Fonts entry to load them in a non-blocking manner. The attribute gets stripped when JS is enabled and the file has loaded. Non-JS browsers will fail to load this font file entirely.
I didn't touch the special fonts in our libraries definitions because the Arabic and Chinese fonts are more necessary to render text properly, so applying this JS-dependent …
=> fix: load primary font in a non-blocking manner

css/brand.css
Refs: CD-527
Remove CSS custom property for mobile logo as it is no longer in use.
It was reverted as part of https://github.com/UN-OCHA/common_design/pull/406 but the variable remains
1. When the CSS variable is present, it appears in the aggregated CSS
None except to remove reference to this in the aggregated CSS
=> CD-527 Remove CSS custom property for mobile logo as it is no longer in use

libraries/cd/cd-header/cd-global-header.css, libraries/cd/cd-header/cd-ocha-services.js, package-lock.json, templates/cd/cd-header/cd-global-header.html.twig
Improves the Cumulative Layout Shift (CLS), a Core Web Vital that is very important to Google and its search results.
1. Load branch and stuff.
2. Using the devtools of your choice, do the following:
- Disable caching, or start with a private browsing window
- Throttle the network to something slow (so that you can see the effect)
3. Load the page and observe that the Help/User menus consistently render to the right of the …
=> [RW-826][CD-530] Reduce CLS in Global Header

common_design.info.yml, common_design_subtheme/.stylelintignore, common_design_subtheme/README.md, common_design_subtheme/css/brand.css, css/brand.css, libraries/cd-author/cd-author.html.twig, libraries/cd-search--inline/cd-search--inline.css, libraries/cd-search/cd-search.css, libraries/cd/cd-header/cd-language-switcher.css
Refs: OPS-9885
After implementing SDC, there was one library `select_a11y` that was still trying to get its CSS from `components` folder.
1. Compare https://web.brand.unocha.org/facets (which is not picking up the styles) with https://feature.commondesign-unocha-org.ahconu.org/facets (which is an old deploy and still picking up styles from components directory due to older base theme version)
2. With the changes in this PR, …
=> OPS-9885 Change directory for select_a11y css after SDC reshuffle

CHANGELOG.md, package-lock.json, package.json
* **perf:** reduce CLS in Global Header ([32f2323](https://github.com/UN-OCHA/common_design/commit/32f2323bf467ecc64c22a8ff9d8c34460bf08dcf))
* Change directory for select_a11y css after SDC reshuffle ([1276855](https://github.com/UN-OCHA/common_design/pull/459/commits/12768555a708cfb6cf8692506b12d6ddf4d0200a))
=> chore(release): 9.3.1

libraries/cd/cd-header/cd-site-header.css
Set flex grow on last child to 0 to prevent full width when wrapping
See CD-538 for screenshots
When there are many menu items, and the viewport approaches 1024px but before the entire menu collapses into the dropdown, the last menu item might wrap and currently it spans 100% of available width (the width of the menu container). This is an edge case and we can see in on unocha.org where there are enough menu items in the …
=> CD-538 Prevent last menu item spanning full width when items wrap

CHANGELOG.md, package-lock.json, package.json
* set flex grow on last child to 0 to prevent full width when wrapping ([6ab5675](https://github.com/UN-OCHA/common_design/commit/6ab5675381e428a42647ed4bf103a3327ae70d3f))
=> chore(release): 9.3.2

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
* OCHA Services moved permanently to the footer - #463
* **security:** jest-puppeteer@10 - #466
* **security:** other npm updates
=> chore(release): 9.3.3

libraries/cd/cd-footer/cd-ocha.css
Refs: CD-537
Design feedback from Javi.
1. Load branch
2. Border should now exist below OCHA Services even on mobile.
CSS only. No impact to existing sub-themes.
=> fix: retain OCHA Services border on mobile

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
* retain OCHA Services border on mobile ([02f1f3b](https://github.com/UN-OCHA/common_design/commit/02f1f3b7632e2d0becaeba0e526cd92110037bf7))
* update example markup for fonts in README ([d59c9e1](https://github.com/UN-OCHA/common_design/commit/d59c9e1a17620b20602e3b6e5c6bfba8ff9fb876))
=> chore(release): 9.3.4

templates/misc/status-messages.html.twig
In theory this should work, as there ought to not be another status messages wrapper.
Refs: OPS-9741
-  Improvement (non-breaking change which iterates on an existing feature)
Add an ID to the main wrapper for status messages, so we can target it for VRT using backstop, so they do not mess with the screenshot diffs.
1. Run VRT as auth user.
2. See login-link-used messages in the screenshots.
3. Oops.
In theory this breaks nothing and fixes something.
=> fix: Add an element id to the outer status messages wrapper div, so backstop can target it.

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
* Non blocking font ([3f58c71](https://github.com/UN-OCHA/common_design/commit/3f58c7150f655c102ff728832fc2ea5d00569ae6), RWR-416, CD-514)
* Add an element id to the outer status messages wrapper div, so backstop can target it. ([70427b3](https://github.com/UN-OCHA/common_design/commit/70427b3262cf6e81b311f51ee32dc640f9fda4aa))
* Mimic Drupal core themes on the status messges wrapper. ([7a4f890](https://github.com/UN-OCHA/common_design/commit/7a4f8903dde890c433d962df1542887d35598196))
=> chore(release): 9.4.0

README.md
Docs-only that I luckily noticed before hitting publish on the latest 9.4.0 release.
Refs: CD-514
=> docs: update example font-loading markup

libraries/cd/cd-footer/cd-footer-mandate.css
While comparing some Strattic CD upgrades this logo was noticeably displaced compared to older versions of the CD. This makes it look more balanced.
Refs: CD-540
CSS nudging.
CSS only, no impact.
=> fix(style): pixel push for mandate logo

libraries/cd/cd-footer/cd-ocha.css
In case the footer color is so light that a different text color is needed, this rule will mean the separator always matches text color.
Refs: CD-547
We had a "hardcoded" CSS Var for OCHA Services separator, but now it uses `currentColor` to make it more override-friendly.
CSS only. No impact.
=> fix(style): OCHA Services separator should inherit color

libraries/cd-form/cd-form.css
When collapsible `<details>` /`<summary>` elements are present, they didn't look clickable. Now they do, and have a background color to show how far they extend. 
1. Load a form that uses the `field_group` module (AI Summarization site has one)
2. Interact with the widget via mouse or keyboard.
CSS only. No impact.
=> [CD-554] default styles for field_group details/summary elements

CHANGELOG.md, common_design_subtheme/package-lock.json, common_design_subtheme/package.json, package-lock.json, package.json
* **style:** apply some default styles to field_group details/summary elements ([6947971](https://github.com/UN-OCHA/common_design/commit/6947971342b897187d3319fd5060010f84df2e9c))
* **style:** OCHA Services separator should inherit color ([4801b3e](https://github.com/UN-OCHA/common_design/commit/4801b3e455b4fbf6175b855e6180627702a0b2e4))
* **style:** pixel push for mandate logo ([f9a4da5](https://github.com/UN-OCHA/common_design/commit/f9a4da588e3c72656c8f9160dc8bb25f8286d30d))
=> chore(release): 9.4.1

common_design.info.yml, common_design.libraries.yml, js/messages.js
Refs: OPS-10532
Discovered during testing feedback from GMS - a change in bigpipe means now theme-hints for status messages don't work as they did. As suggested in https://www.drupal.org/project/drupal/issues/3456176, we now should theme them in a js template rather than through twig. Leaving the twig template for status messages that aren't handled by js.
1. Trigger a status message on a non-admin page.
How does the …
=> chore: style status messages for 10.3

common_design.libraries.yml
Refs: OPS-10532
-  Improvement (non-breaking change which iterates on an existing feature)
I tested the last change in a site using an old version of CD - components should now be in the `libraries/` directory. This fixes that.
Bug fix from last release.
- [ x] I have followed the Conventional Commits guidelines.
=> chore: use updated path for component libraries
